gce-xfstests: add support for arm64
Add arm64 support to build-appliance script, gce-xfstests shell, ltm,
and kcs.

Running gce-xfstests:
    Default ARCH can be set in ~/.config/gce-xfstests which affects
    commands run through gce-xfstests command. The flag --arch <arch>
    is also supported and will override the ARCH set in config.

Building test appliance:
    The build attempts to detect architecture from build chroot. If
    this cannot be detected, default to amd64 or whatever is set in
    config.custom.

Testing Plan:
   # ensure amd64 build / shell still work
   ./build-appliance
   gce-xfstests create-image  # xfstests-amd64-<datecode>
   gce-xfstests shell

   # test arch flags
   ./build-appliance --chroot <arm-chroot>
   gce-xfstests create-image --arch arm64  # xfstests-arm64-<datecode>
   gce-xfstests shell --arch arm64

   # ensure packages working for arm64
   gce-xfstests ltm -c ext4/4k -g auto --arch arm64

   # test ARCH config
   ./build-appliance --chroot <arm-chroot>
   # ARCH=arm64 in ~/.config/gce-xfstests
   gce-xfstests create-image  # xfstests-arm64-<datecode>
   gce-xfstests shell         # uses arm VM and pulls ARM image

   # remove ARCH from ~/.config/gce-xfstests
   # test build-appliance with --gce flag
   ./build-appliance --chroot <arm-chroot> --gce
   gce-xfstests shell           # make sure pulls from latest x86 image even though arm built last
   gce-xfstests shell --arch arm64

   # ensure amd64 ltm/kcs not broken
   gce-xfstests launch-ltm
   gce-xfstests ltm -c ext4/4k,ext4/1k generic/001 --kernel <kernel>
   gce-xfstests ltm -c ext4/4k ext4/1k generic/001 --commit <commit>

   # test ltm arm64 flag
   gce-xfstests launch-ltm --arch arm64
   gce-xfstests ltm -c ext4/4k,ext4/1k generic/001 --kernel <arm-kernel>
     --arch arm64 --no-region-shard
   gce-xfstests ltm -c ext4/4k,ext4/1k generic/001 --kernel <amd-kernel>
   gce-xfstests ltm -c ext4/4k,ext4/1k generic/001 --kernel <arm64-kernel>
     --arch amd64

   # test arm64 ltm through config
   # ARCH=arm64 in ~/.config/gce-xfstests
   gce-xfstests launch-ltm
   gce-xfstests ltm -c ext4/4k ext4/1k generic/001 --commit <commit>

Signed-off-by: Leah Rumancik <leah.rumancik@gmail.com>

diff --git a/run-fstests/util/gce-launch-kcs b/run-fstests/util/gce-launch-kcs
--- a/run-fstests/util/gce-launch-kcs
+++ b/run-fstests/util/gce-launch-kcs
@@ -16,15 +16,33 @@ then
 fi
 
 . "$DIR/util/get-config"
+. "$DIR/util/gce-helper-funcs"
 
-case $1 in
-    --image-project) shift
-    GCE_IMAGE_PROJECT="$1"
-    shift ;;
-esac
+while (( $# >= 1 )); do
+    case $1 in
+	--image-project) shift
+	    GCE_IMAGE_PROJECT="$1"
+	    ;;
+	--arch) shift
+	    ARCH="$1"
+	    ;;
+	*)
+	    echo "Invalid option \"$1\""
+	    shift
+	    ;;
+    esac
+    shift
+done
 
-if [ -z "$GCE_IMAGE_PROJECT" ]; then
+get_arch "$ARCH"
+
+if test -z "$GCE_IMAGE_PROJECT" ; then
     GCE_IMAGE_PROJECT="xfstests-cloud"
+fi
+
+if test -n "$USING_DEFAULT_FAMILY" ; then
+    ROOT_FS="xfstests-$ARCH"
+    IMAGE_FLAG="--image-family"
 fi
 
 INSTANCE="xfstests-kcs"
@@ -35,9 +53,19 @@ if test -f "$DIR/.kcs_cookie_$GCE_PROJECT"; then
 fi
 
 NO_ACTION=
-if run_gcloud compute instances describe --zone $GCE_ZONE \
-    $INSTANCE >& /dev/null
+
+DESCRIBE=$(run_gcloud_always compute instances describe \
+    --zone $GCE_ZONE $INSTANCE 2> /dev/null)
+if test -n "$DESCRIBE"
 then
+    KCS_ARCH=$(echo "$DESCRIBE" | sed -rn 's/.*architecture: (.*)/\1/p' )
+
+    if test "$KCS_ARCH" != "$GCE_ARCH"; then
+	echo "KCS server is already running on $KCS_ARCH instance but $ARCH requested."
+	echo "Please delete the KCS instance and try again."
+	exit 1
+    fi
+
     if [ -f $DIR/.kcs_instance_$GCE_PROJECT ]
     then
 	echo "The KCS instance already exists!"
@@ -60,8 +88,15 @@ then
     exit 1
 fi
 
-if [ -z "$GCE_KCS_MACHTYPE" ]; then
-	GCE_KCS_MACHTYPE="n2-standard-4"
+if test -z "$GCE_KCS_MACHTYPE" ; then
+    case "$ARCH" in
+	amd64)
+	    GCE_KCS_MACHTYPE="n2-standard-4"
+	    ;;
+	arm64)
+	    GCE_KCS_MACHTYPE="t2a-standard-4"
+	    ;;
+    esac
 fi
 
 GS_RW=https://www.googleapis.com/auth/devstorage.read_write
