gce-xfstests: add support for arm64
Add arm64 support to build-appliance script and gce-xfstests shell.

Tested:
  sudo ./build-appliance
  gce-xfstests create-image
  gce-xfstests shell

  sudo ./build-appliance --chroot <arm-chroot>
  gce-xfstests create-image --arch=arm64
  gce-xfstests shell --arch=arm64

  gce-xfstests shell  # defaults to amd64 image

  sudo ./build-appliance --chroot <arm-chroot> --gce
  gce-xfstests shell
  gce-xfstests shell --arch=arm64

  delete xfstests-<arch>-<datecode> images
  gce-xfstests shell # reverts to old image name lookup

Signed-off-by: Leah Rumancik <leah.rumancik@gmail.com>

TODO: should we make ARCH a config parameter? right now it is all flags
TODO: should we separate into separate image families? right now it is
based on file name, file names expected to be of format
xfstests-$ARCH-$DATECODE. should this name format be relaxed?
TODO: figure out why those packages aren't installing

diff --git a/build-appliance b/build-appliance
--- a/build-appliance
+++ b/build-appliance
@@ -11,6 +11,7 @@ OUT_TAR=
 BUILD_ENV=
 SUDO_ENV=sudo
 DO_GCE=
+ARCH=amd64
 
 if test -f config.custom ; then
     . config.custom
@@ -92,6 +93,36 @@ if $UPDATE && [ "$OUT_TAR" = "yes" ]; then
     exit 1
 fi
 
+CHROOT=$(sed -n "s/.*-c\s\+\(.*\)\s\+.*/\1/p" <<< "$BUILD_ENV")
+
+if test ! "$CHROOT"; then
+	echo "Warning: failed to detect chroot name"
+fi
+
+# TODO: this will break if not using the default of description formatting
+# SCHROOT_CHROOT_D=/etc/schroot/chroot.d in setup-buildchroot
+ARCH=$(sed -n "s/^description=.*(\(.*\))$/\1/p" \
+	/etc/schroot/chroot.d/$CHROOT)
+
+if test -n "$ARCH"; then
+	echo "Detected architecture of chroot as $ARCH"
+else
+	echo "Warning: failed to detect architecture of chroot,"
+	echo "using default architecture of $ARCH"
+fi
+
+case "$ARCH" in
+    x86-64|x86_64|amd64)
+	ARCH="amd64"
+	;;
+    arm64)
+	;;
+    *)
+	echo "Architecture $ARCH not supported"
+	exit 1
+	;;
+esac
+
 cd fstests-bld
 
 if $UPDATE; then
@@ -109,7 +140,7 @@ esac
 
 cd ../run-fstests
 if test -n "$DO_GCE"; then
-    ./gce-xfstests create-image >& /tmp/gce-xfstests-create.$$ &
+    ./gce-xfstests create-image --arch=$ARCH >& /tmp/gce-xfstests-create.$$ &
 fi
 
 cd ../test-appliance
diff --git a/run-fstests/gce-xfstests b/run-fstests/gce-xfstests
--- a/run-fstests/gce-xfstests
+++ b/run-fstests/gce-xfstests
@@ -3,6 +3,7 @@
 XFSTESTS_FLAVOR=gce
 RUN_ON_LTM=
 RUN_ON_KCS=
+ARCH=amd64
 t=$(echo ${XFSTESTS_FLAVOR}_xfstests_dir | tr "[:lower:]" "[:upper:]")
 eval DIR="\$$t"
 if test -z "$DIR"
@@ -944,6 +945,7 @@ then
 fi
 
 # MT_PRICE is in millidollars, as of 9/7/2015
+# MT_PRICE for arm64 (t2a) updated 09/15/2022
 function get_machtype_stats() {
     local mt=$1
     case "$mt" in
@@ -983,6 +985,13 @@ function get_machtype_stats() {
 	n1-standard-64)	MT_PRICE=3040	; MT_CPU=64  ; MT_RAM=245760 ;;
 	n1-highmem-64)	MT_PRICE=3789	; MT_CPU=64  ; MT_RAM=425984 ;;
 	n1-highcpu-64)	MT_PRICE=2269	; MT_CPU=64  ; MT_RAM=58982 ;;
+	t2a-standard-1)		MT_PRICE=0039; MT_CPU=1   ; MT_RAM=4096 ;;
+	t2a-standard-2)		MT_PRICE=0077; MT_CPU=2   ; MT_RAM=8192 ;;
+	t2a-standard-4)		MT_PRICE=0154; MT_CPU=4   ; MT_RAM=16384 ;;
+	t2a-standard-8)		MT_PRICE=0308; MT_CPU=8   ; MT_RAM=32768 ;;
+	t2a-standard-16)	MT_PRICE=0616; MT_CPU=16  ; MT_RAM=65536 ;;
+	t2a-standard-32)	MT_PRICE=1232; MT_CPU=32  ; MT_RAM=131072 ;;
+	t2a-standard-48)	MT_PRICE=1848; MT_CPU=48  ; MT_RAM=196608 ;;
 	*) MT_PRICE=0	; MT_CPU=0  ; MT_RAM=0 ;;
     esac
 }
@@ -997,9 +1006,19 @@ function fit_machtype_resources() {
     get_machtype_file
     while read f_machtype  f_zone f_cpus f_memory
     do
-	case "$f_machtype" in
-	    n2-*|c2-*) continue ;;
-	    e2-*)	if test -n "$DO_LOCAL_SSD" ; then continue ; fi ;;
+	case "$ARCH" in
+	    arm64)
+		case "$f_machtype" in
+		    t2a-*) ;;
+		    *) continue ;;
+		esac
+		;;
+	    amd64)
+		case "$f_machtype" in
+		    n2-*|c2-*|t2a-*) continue ;;
+		    e2-*)	if test -n "$DO_LOCAL_SSD" ; then continue ; fi ;;
+		esac
+		;;
 	esac
 	if test "$GCE_ZONE" != "$f_zone" ; then
 	    continue
@@ -1018,6 +1037,15 @@ function fit_machtype_resources() {
 	fi
     done < $GCE_MACHTYPE_FILE
     GCE_MACHTYPE="$cur_machtype"
+
+    if test -z "$GCE_MACHTYPE"; then
+	    echo "Could not find a machine matching the provided criteria."
+	    if test "$ARCH" = "arm64" ; then
+		    echo "For arm64, make sure you are using a zone that has t2a machines."
+	    fi
+	    exit 1
+    fi
+
     get_machtype_stats "$GCE_MACHTYPE"
 }
 
@@ -1102,6 +1130,36 @@ else
     # echo "Using ARG: $ARG"
 fi
 
+if test "$IMAGE_FLAG" = "--image-family" ; then
+	FAMILY_FILTER="--filter=\"family <= $ROOT_FS AND family >= $ROOT_FS\""
+elif test "$IMAGE_FLAG" = "--image"; then
+	IMAGE="$ROOT_FS"
+fi
+
+#TODO update filter by name? name might  not always be "xfstests..."
+# first search for images with architecture in name
+if test ! -n "$IMAGE"; then
+	IMAGE=$(run_gcloud_always compute images list \
+		--no-standard-images \
+		--project "${GCE_IMAGE_PROJECT:-xfstests-cloud}" \
+		"$FAMILY_FILTER" \
+		--filter="name~xfstests-$ARCH-[0-9]+" \
+		--sort-by=~name --limit 1 2>/dev/null | \
+		grep -oE "xfstests-$ARCH-[0-9]+")
+fi
+
+#TODO update filter by name? name might  not always be "xfstests..."
+# fall back to use names without architectures
+if test ! -n "$IMAGE"; then
+	IMAGE=$(run_gcloud_always compute images list \
+		--no-standard-images \
+		--project "${GCE_IMAGE_PROJECT:-xfstests-cloud}" \
+		"$FAMILY_FILTER" \
+		--filter="name~xfstests-[0-9]+" \
+		--sort-by=~name --limit 1 | \
+		grep -oE "xfstests-[0-9]+")
+fi
+
 run_gcloud compute \
        instances create "$INSTANCE" --zone "$GCE_ZONE" \
        --machine-type "$GCE_MACHTYPE" --network "$GCE_NETWORK" \
@@ -1110,8 +1168,7 @@ run_gcloud compute \
        --scopes "$SCOPES" \
        --metadata "^ ^$ARG" \
        --tags http-server,https-server \
-       --image-project "${GCE_IMAGE_PROJECT:-xfstests-cloud}" \
-       "$IMAGE_FLAG" "$ROOT_FS"
+       --image="$IMAGE"
 
 case "$ARG" in
     cmd=maint*)
